esphome:
  name: sha2017-badge
  friendly_name: sha2017 badge

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "changethisintosomethingnew"

ota:
  - platform: esphome
    password: "andchangethisintosomethingelse"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sha2017-Badge Fallback Hotspot"
    password: "anothersecretyourshouldchange"

captive_portal:

i2c:
  sda: 26
  scl: 27
  scan: True

mpr121:
  id: mpr121_component
  address: 0x5A
  touch_debounce: 1
  release_debounce: 1
  touch_threshold: 12
  release_threshold: 6

binary_sensor:
  - platform: mpr121
    id: touch_buttonA
    channel: 0
    name: "Touch Button A"
  - platform: mpr121
    id: touch_buttonB
    channel: 1
    name: "Touch Button B"
  - platform: mpr121
    id: touch_buttonStart
    channel: 2
    name: "Touch Button Start"
  - platform: mpr121
    id: touch_buttonSelect
    channel: 3
    name: "Touch Button Select"
  - platform: mpr121
    id: touch_buttonDown
    channel: 4
    name: "Touch Button Down"
  - platform: mpr121
    id: touch_buttonRight
    channel: 5
    name: "Touch Button Right"
  - platform: mpr121
    id: touch_buttonUp
    channel: 6
    name: "Touch Button Up"
  - platform: mpr121
    id: touch_buttonLeft
    channel: 7
    name: "Touch Button Left"
  - platform: mpr121
    id: charging_status
    channel: 9
    name: "Charging Status"
  - platform: gpio
    name: "Flash Button"
    pin: 0
    filters:
      - invert:

sensor:
  - platform: adc
    pin: 34
    attenuation: 6db
    filters:
      - multiply: 2.91
    name: "USB Voltage"
    update_interval: 20s
    accuracy_decimals: 1
  - platform: adc
    pin: 35
    attenuation: 6db
    #attenuation: 2.5db
    filters:
      - multiply: 2.91
      #- multiply: 1.95
    name: "Battery Voltage"
    update_interval: 20s
    accuracy_decimals: 1

spi:
  clk_pin: 18
  mosi_pin: 5

font:
  - file: "gfonts://Roboto"
    id: roboto_24
    size: 24

external_components:
  - source: github://SqyD/esphome/@dke2.9-epaper
    components: [ waveshare_epaper ]

image:
  - file: mdi:home-assistant
    id: ha_icon
    resize: 80x80

display:
  - platform: waveshare_epaper
    id: my_display
    cs_pin: 19
    dc_pin: 21
    busy_pin: 22
    reset_pin: 23
    model: 2.90in-dke
    auto_clear_enabled: false
    update_interval: never
    rotation: 270
    lambda: |-
      it.print(0, 0, id(roboto_24), "Hello Badge Team!");
      it.image(200, 20, id(ha_icon));