esphome:
  name: mch2022-badge
  friendly_name: mch2022 badge
  libraries:
    - appfs=https://github.com/badgeteam/esp32-component-appfs.git#b20b1d8
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_SPI_FLASH_DANGEROUS_WRITE_ALLOWED: y
  partitions: mch2022-badge/partitions.csv
  flash_size: 16MB

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "changethisintosomethingnew"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mch2022-Badge Fallback Hotspot"
    password: "andchangethisintosomethingelse"

captive_portal:

external_components:
  - source: github://SqyD/esphome/@spi_dma
    components: [ ili9xxx ]
  - source:
      type: git
      url: https://github.com/badgeteam/esphome-badge
      ref: master
      path: mch2022/components
    components: [ mch2022_rp2040 ]
    refresh: 1s


switch:
  - platform: gpio
    pin: 19
    name: "Kite Lights Switch"
    id: kite_light_switch
    internal: True
  - platform: gpio
    pin: 26
    restore_mode: ALWAYS_OFF
    name: "LCD Mode"
    internal: True

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 5
    num_leds: 5
    rmt_channel: 0
    chipset: SK6812
    name: "Kite Leds"
    on_turn_on:
      then:
        - switch.turn_on: kite_light_switch
    on_turn_off:
      then:
        - switch.turn_off: kite_light_switch

i2c:
  sda: GPIO22
  scl: GPIO21
  scan: True

sensor:
  - platform: bme680
    temperature:
      name: "BME680 Temperature"
      oversampling: 16x
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    gas_resistance:
      name: "BME680 Gas Resistance"
    address: 0x77
    update_interval: 60s

spi:
  clk_pin: 18
  mosi_pin: 23

display:
  - platform: ili9xxx
    model: ili9341
    id: badge_display
    setup_priority: 600
    dc_pin: 33
    reset_pin: 25
    cs_pin: 32
    transform:
      swap_xy: true
    dimensions: 
      width: 320
      height: 240
    invert_colors: false
    auto_clear_enabled: false
    update_interval: never

lvgl:
  displays:
    - badge_display
    - keypads:
      home: buttonHOME
  pages:
    - id: main_page
      widgets:
        - label:
            align: CENTER
            text: 'Hello Badge Team!'


mch2022_rp2040:
  - id: 'mch2022_rp2040_io'

binary_sensor:
  - platform: mch2022_rp2040
    input: button_home
    id: buttonHOME
  - platform: mch2022_rp2040
    input: button_menu
    id: buttonMENU
  - platform: mch2022_rp2040
    input: button_start
    id: buttonSTART
  - platform: mch2022_rp2040
    input: button_accept
    id: buttonACCEPT
  - platform: mch2022_rp2040
    input: button_back
    id: buttonBACK
  - platform: mch2022_rp2040
    input: button_select
    id: buttonSELECT
  - platform: mch2022_rp2040
    input: joystick_left
    id: joystickLEFT
  - platform: mch2022_rp2040
    input: joystick_press
    id: joystickPRESS
  - platform: mch2022_rp2040
    input: joystick_down
    id: joystickDOWN
  - platform: mch2022_rp2040
    input: joystick_up
    id: joystickUP
  - platform: mch2022_rp2040
    input: joystick_right
    id: joystickRIGHT

