esphome:
  name: mch2022-badge
  friendly_name: mch2022 badge
  libraries:
    - appfs=https://github.com/badgeteam/esp32-component-appfs.git#b20b1d8
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    # version: 4.4.4
    sdkconfig_options:
      CONFIG_SPI_FLASH_DANGEROUS_WRITE_ALLOWED: y
  partitions: mch2022-badge/partitions.csv
  flash_size: 16MB

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "changethisintosomethingnew"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mch2022-Badge Fallback Hotspot"
    password: "andchangethisintosomethingelse"

captive_portal:

switch:
  - platform: gpio
    pin: 19
    name: "Kite Lights Switch"

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 5
    num_leds: 5
    rmt_channel: 0
    chipset: ws2812
    name: "Kite Leds"

i2c:
  sda: GPIO22
  scl: GPIO21
  scan: True

sensor:
  - platform: bme680
    temperature:
      name: "BME680 Temperature"
      oversampling: 16x
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    gas_resistance:
      name: "BME680 Gas Resistance"
    address: 0x77
    update_interval: 60s

# WARNING: All the sections below are currently not working
# The display is sharing the SPI bus with the FPGA chip on the badge. Not sure if that's relevant.

font:
  - file: "gfonts://Roboto"
    id: roboto_24
    size: 24

image:
  - file: mdi:home-assistant
    id: ha_icon
    resize: 80x80

spi:
  clk_pin: 18
  mosi_pin: 23

display:
  - platform: ili9xxx
    model: ili9341
    dc_pin: 33
    reset_pin: 25
    cs_pin: 32
    lambda: |-
      it.print(0, 0, id(roboto_24), "Hello Badge Team!");
      it.image(200, 20, id(ha_icon));  